service: aws-node-rest-api

frameworkVersion: '4'


provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          
